ARG version
FROM almalinux:${version:-8}
#RUN cat /etc/os-release
ARG course=docker
ARG trainer=sivakumar
ENV duration=100hrs
RUN echo course is ${course} and trainer is ${trainer}
CMD [ "sleep", "100"]

